[tool.coverage.run]
source = [
  "src/application",
  "src/domain",
]
# (Opcional) si quieres excluir helpers o tipos
omit = [
  "**/__init__.py",
]

[tool.coverage.report]
show_missing = true
skip_empty = true